version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      TZ: America/Recife
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"
    networks:
      - wordpress-network
  
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - /mnt/efs/filipe-gomes/var/www/html:/var/www/html
    environment:
      TZ: America/Recife
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: teste
      WORDPRESS_DB_PASSWORD: teste
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge